### ISSUE TITLE
MCP server build check: reproduce services_tools.rs failure

### ISSUE THREAD

**Issue by jayminwest** [kotadb/kota-db#734]
## Summary
Re-check the MCP server build failures reported in #534 using the current toolchain, and capture the new error signature (or close if resolved).

## Current State
- Builders previously hit a compilation error in `services_tools.rs`, but the code has since been refactored.
- No recent reproduction exists, and CI currently passes.
- We need a scoped task to re-run the build on macOS/Linux and either fix or document the outcome.

## Proposed Steps
1. Run `cargo build --bin mcp_server --features "mcp-server"` on macOS and Linux containers.
2. If failures reappear, capture full logs and open targeted bug(s).
3. Update docs/CI scripts to ensure the MCP server build step runs in `just ci-fast` going forward.
4. Close the legacy issue referencing the new results.

## Acceptance Criteria
- Build reproduction attempt documented (including platform, command, logs).
- If the build now succeeds, confirm `just ci-fast` covers it; if not, create specific bug issue(s).
- Legacy issue #534 closed with reference to this tracking issue.

## Follow-up
- Close #534 when this issue is created.
